### ISSUE TITLE
Effective condolences positive and negative samples

### ISSUE THREAD

**Issue by wangjs9** [naitian/Condolence-Empathy-Online-Communities#1]
I am interested in your work after reading you paper. But I have a question that how to obtain the dataset of effectiveness condolence classification (Sec 7 What makes a good condolence?).

Another question is that I find the definition of condolence can be summerized as an expression of sympathy. However, many cited papers in this paper argues the definition of condolence is sympathy with a person in grief. Therefore, I am not sure about the meaning of condolence this paper focuses.

**Comment by naitian** [comment]
Hi Jessie, thanks for your interest! 

To obtain the dataset of effective condolences, we look at the children comment of condolences and filter for appreciative comments (those containing certain high-precision appreciative phrases e.g. "thank you" or "this made my day"). We mark these as "effective". This is a relatively low-fidelity analysis, and could be interesting to explore further.

In our work, we make a distinction between empathetic and sympathetic condolences, both of which exist. Sympathetic condolences are often trite, highly-repeated phrases like "sorry for your loss" which engage with what happened to the condolence seeker. Empathetic condolences demonstrate that the condolence-giver relates emotionally to the condolence-seeker. Again, both types exist, but we make this distinction because some prior works (referenced in the paper) show that different kinds of grief responses have varying levels of helpfulness.

**Comment by wangjs9** [comment]
Thank you for your reply!!!

But I think that my questions are not clear enough.

I have the first question because the paper mentions that there are 23,301 and 149,992 positive and negative effective condolence samples. But I cannot find these two numbers nor their sum in the paper/data. Therefore, I wonder where the samples are from? Are they contained in the dataset of condolence_pos? And how can I use the id to get the content?
BTW, I am really intertested in the problem of effectiveness of empathetic expression / supportive messages. Therefore, I am really excited that I find some other people have a similar idea. 

And another question is that the direct meaning of condolence is to express empathy/sympathy to people who suffer the death of their friends, relatives, pet... But I find that various topics are contained in the datatset, therefore I wonder is the condolence in your paper about empathetic/sypathteic expression to negative emotions because of diverse causes (not only death)?

Thank you again!!!
